services:
  - name: your-service-name
    runtime: node
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    region: oregon
    branch: main
    envVars:
      XDG_CONFIG_HOME: "/home/render/.config"
      PATH: "/home/render/.config/npm/node_global/bin:/home/render/node_modules/.bin"
      npm_config_prefix: "/home/render/.config/npm/node_global"
    disk:
      - name: config
        mountPath: /home/render/.config
    extraPorts:
      - internalPort: 80
        externalPort: 80
